# Generated by Django 3.1.3 on 2020-11-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_path',
            new_name='image',
        ),
    ]
