# Generated by Django 3.1.3 on 2020-11-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201122_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
