# Generated by Django 3.1.3 on 2020-11-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201125_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(default='image/upload/v1606300231/gzwpgegxjpsonlkjrviq.svg', on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
